inherit_from: .rubocop_todo.yml

Style/ClassCheck:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/PredicateName:
  Enabled: false

AllCops:
  Exclude:
    - 'app/models/bksb.rb'
