views:
  - id: 1
    icon: fa-home
    title: Home
    topic_person: true
    topic_course: true
    controls: null
    view_type: timeline
    events: 
      Attendance:
        null
      ContactLog:
        null
      PersonCourse:
        null
      Disciplinary:
        null
      Note:
        null
      Target:
        null
      Review:
        null
      ReviewLine:
        null
      Qualification:
        null
      SupportRequest:
        null
      SupportHistory:
        null
      InitialReview:
        null
      Intervention:
        null
      SupportStrategy:
        null
      Absence:
        null
    url: all
    aff_affiliate: true
    aff_applicant: true
    aff_staff: true
    aff_student: true
    admin_only: false
  - id: 2
    parent_id: 1
    icon: fa-bullseye
    title: Targets
    topic_person: true
    topic_course: true
    controls: null
    view_type: timeline
    events: 
      Target:
        - overdue
    url: targets
    aff_affiliate: true
    aff_applicant: true
    aff_staff: true
    aff_student: true
    admin_only: false
