views:
  - id: 1
    icon: fa-home
    title: Home
    topic_person: Yes
    topic_course: Yes
    controls: null
    view_type: timeline
    events: 
      Attendance:
        null
      MdlBadge:
        null
      ContactLog:
        null
      PersonCourse:
        null
      Disciplinary:
        null
      Note:
        null
      Target:
        null
      Review:
        null
      ReviewLine:
        null
      Qualification:
        null
      SupportRequest:
        null
      SupportHistory:
        null
      InitialReview:
        null
      Intervention:
        null
      SupportStrategy:
        null
      Absence:
        null
    url: all
    aff_affiliate: Yes
    aff_applicant: Yes
    aff_staff: Yes
    aff_student: Yes
    admin_only: no
  - id: 2
    parent_id: 1
    icon: fa-bullseye
    title: Targets
    topic_person: Yes
    topic_course: Yes
    controls: null
    view_type: timeline
    events: 
      Target:
        - overdue
    url: targets
    aff_affiliate: Yes
    aff_applicant: Yes
    aff_staff: Yes
    aff_student: Yes
    admin_only: no
  - id: 3
    parent_id: 1
    icon: fa-dot-circle-o
    title: Badges
    topic_person: Yes
    topic_course: Yes
    controls: null
    view_type: tiles
    events: 
      MdlBadge:
        null
    url: badges
    aff_affiliate: Yes
    aff_applicant: Yes
    aff_staff: Yes
    aff_student: Yes
    admin_only: no
  - id: 4
    parent_id: 1
    icon: fa-comment
    title: Contact Logs
    topic_person: Yes
    topic_course: Yes
    controls:
      - name: Add a Contact Log
        templateUrl: contact_log.html
      - name: Plopt
        templateUrl: contact_log.html
    view_type: tiles
    events: 
      ContactLog:
        null
    url: contact-logs
    aff_affiliate: Yes
    aff_applicant: Yes
    aff_staff: Yes
    aff_student: Yes
    admin_only: no
