views:
  - id: 1
    icon: fa-home
    title: Home
    topic_person: Yes
    topic_course: Yes
    controls: null
    view_type: timeline
    events: 
      Attendance:
        null
      MdlBadge:
        null
      ContactLog:
        null
      PersonCourse:
        null
      Disciplinary:
        null
      Note:
        null
      Target:
        null
      Review:
        null
      ReviewLine:
        null
      Qualification:
        null
      SupportRequest:
        null
      SupportHistory:
        null
      InitialReview:
        null
      Intervention:
        null
      SupportStrategy:
        null
      Absence:
        null
    url: all
    aff_affiliate: Yes
    aff_applicant: Yes
    aff_staff: Yes
    aff_student: Yes
    admin_only: no
  - id: 2
    parent_id: 1
    icon: fa-bullseye
    title: Targets
    topic_person: Yes
    topic_course: Yes
    controls: null
    view_type: timeline
    events: 
      Target:
        - overdue
    url: targets
    aff_affiliate: Yes
    aff_applicant: Yes
    aff_staff: Yes
    aff_student: Yes
    admin_only: no
    controls:
      - name: Add a Target
        templateUrl: target.html
        createEvent: target
  - id: 3
    parent_id: 1
    icon: fa-dot-circle-o
    title: Badges
    topic_person: Yes
    topic_course: Yes
    controls: null
    view_type: tiles
    events: 
      MdlBadge:
        null
    url: badges
    aff_affiliate: Yes
    aff_applicant: Yes
    aff_staff: Yes
    aff_student: Yes
    admin_only: no
  - id: 4
    parent_id: 1
    icon: fa-comment
    title: Contact Logs
    topic_person: Yes
    topic_course: Yes
    controls:
      - name: Add a Contact Log
        templateUrl: contact_log.html
        createEvent: contact_log
    view_type: timeline
    events: 
      ContactLog:
        null
    url: contact-logs
    aff_affiliate: Yes
    aff_applicant: Yes
    aff_staff: Yes
    aff_student: Yes
    admin_only: no
  - id: 5
    parent_id: null
    icon: fa-mortar-board
    title: Courses
    topic_person: Yes
    topic_course: No
    controls: null
    view_type: timeline
    events: 
      PersonCourse:
        - start
    url: courses
    aff_affiliate: Yes
    aff_applicant: Yes
    aff_staff: Yes
    aff_student: Yes
    admin_only: no
  - id: 6
    parent_id: 5
    icon: fa-certificate
    title: Qualifications
    topic_person: Yes
    topic_course: Yes
    controls: 
      - name: Quals on Entry
        templateUrl: qoe.html
    view_type: table
    events: 
      Qualification:
        - create
    url: qualifications
    aff_affiliate: Yes
    aff_applicant: Yes
    aff_staff: Yes
    aff_student: Yes
    admin_only: no

categories:
  - id: 1
    title: Core
    color: "#4f2170"
  - id: 2
    title: English
    color: "#1a695e"
  - id: 3
    title: Maths
    color: "#a75d29"
  - id: 4
    title: PPD
    color: "#a7a429"
